export interface PlaygroundWork {
  /** public/playground/ 아래 파일 경로 */
  src: string;
  title: string;
  /** "클라이언트 · 소속" 형식 — 캡션 둘째 칸 */
  client: string;
  year: string;
  /** 원본 픽셀 크기 — 열이 지연 로딩 중에 튀지 않도록 자리를 미리 잡는다 */
  width: number;
  height: number;
  /**
   * 세로로 긴 이미지 표시. 지금은 아무 동작도 걸려 있지 않다 —
   * 산출물이 넘겨준 큐레이션 데이터라 그대로 보존만 한다.
   */
  tall: boolean;
}

/*
 * 순서·문구·포함 목록은 소유자가 확정한 큐레이션이다. 정렬을 바꾸거나 문구를
 * 다듬거나 항목을 빼지 않는다 — 강한 작업(WELLFISH)이 첫 화면, 오래된 작업
 * (B tv)이 마지막이라는 배치 자체가 결정 사항이다.
 * 판정 근거는 레포 루트 playground.md 에 남아 있다.
 */
export const PLAYGROUND_WORKS: PlaygroundWork[] = [
  {
    src: "/playground/wellfish-01-apparel.webp",
    title: "WELLFISH 어패럴",
    client: "WELLFISH · 로셜컴퍼니",
    year: "2021",
    width: 1800,
    height: 1200,
    tall: false,
  },
  {
    src: "/playground/wellfish-02-package.webp",
    title: "WELLFISH 캔 패키지",
    client: "WELLFISH · 로셜컴퍼니",
    year: "2021",
    width: 1800,
    height: 1350,
    tall: false,
  },
  {
    src: "/playground/wellfish-03-billboard.webp",
    title: "WELLFISH 옥외 광고",
    client: "WELLFISH · 로셜컴퍼니",
    year: "2021",
    width: 1800,
    height: 1200,
    tall: false,
  },
  {
    src: "/playground/hifive-01-banner.webp",
    title: "HI-FIVE 데모데이 배너",
    client: "HI-FIVE · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1200,
    tall: false,
  },
  {
    src: "/playground/hifive-02-outdoor.webp",
    title: "HI-FIVE 옥외 포스터",
    client: "HI-FIVE · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1240,
    tall: false,
  },
  {
    src: "/playground/hifive-03-poster.webp",
    title: "HI-FIVE 모집 포스터",
    client: "HI-FIVE · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1280,
    tall: false,
  },
  {
    src: "/playground/ipsl-01-flag.webp",
    title: "IPSL 데모데이 플래그",
    client: "IPSL · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1200,
    tall: false,
  },
  {
    src: "/playground/ipsl-03-poster.webp",
    title: "IPSL 행사 포스터",
    client: "IPSL · 로셜컴퍼니",
    year: "2022",
    width: 1273,
    height: 1800,
    tall: true,
  },
  {
    src: "/playground/ipsl-02-card.webp",
    title: "IPSL 명함",
    client: "IPSL · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1385,
    tall: false,
  },
  {
    src: "/playground/hangang-01-web.webp",
    title: "한강그룹 웹사이트",
    client: "한강그룹 · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1013,
    tall: false,
  },
  {
    src: "/playground/hangang-02-web.webp",
    title: "한강그룹 웹사이트",
    client: "한강그룹 · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1013,
    tall: false,
  },
  {
    src: "/playground/dooravel-01-mobile.webp",
    title: "두레블 모바일",
    client: "두레블 · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1200,
    tall: false,
  },
  {
    src: "/playground/dooravel-02-screen.webp",
    title: "두레블 화면 설계",
    client: "두레블 · 로셜컴퍼니",
    year: "2022",
    width: 1362,
    height: 1800,
    tall: true,
  },
  {
    src: "/playground/dooravel-03-screen.webp",
    title: "두레블 화면 설계",
    client: "두레블 · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1680,
    tall: false,
  },
  {
    src: "/playground/dooravel-04-screen.webp",
    title: "두레블 화면 설계",
    client: "두레블 · 로셜컴퍼니",
    year: "2022",
    width: 1403,
    height: 1800,
    tall: true,
  },
  {
    src: "/playground/dooravel-05-screen.webp",
    title: "두레블 화면 설계",
    client: "두레블 · 로셜컴퍼니",
    year: "2022",
    width: 1800,
    height: 1285,
    tall: false,
  },
  {
    src: "/playground/btv-00-cover.webp",
    title: "B tv 홈 화면 종합",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-01-guideline.webp",
    title: "B tv 디자인 가이드라인",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-02-banner-spec.webp",
    title: "B tv 배너 규격 시스템",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-03-tvseries.webp",
    title: "B tv 시리즈 홈 화면",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-04-tvseries.webp",
    title: "B tv 시리즈 홈 화면",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-05a-movie-banners.webp",
    title: "B tv 영화 배너 모음",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-05-promotion.webp",
    title: "B tv 영화 프로모션",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-06-banners.webp",
    title: "B tv 배너·이벤트 모음",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-07-kids.webp",
    title: "B tv 키즈 프로모션",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-08-kids-story.webp",
    title: "B tv 키즈 동화 화면",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-09-kids-home.webp",
    title: "B tv 키즈 홈 화면",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },
  {
    src: "/playground/btv-10-kids-event.webp",
    title: "B tv 키즈 이벤트",
    client: "SK B tv · 아메바",
    year: "2020–2021",
    width: 1800,
    height: 1010,
    tall: false,
  },];
